### ISSUE TITLE
US3: Add filter button

### ISSUE THREAD

**Issue by NirachaMarchett** [NirachaMarchett/recap-project-3_rick-and-morty-app#6]
### Value proposition
As a user
I want to search for items using filter 
so that I can find all items that have the same remaining days at once. 

### Description

![Image](https://user-images.githubusercontent.com/135506311/257632966-44cdd99f-7d6e-4940-b38c-dd01c6924f06.png)

### Acceptance criteria

- [ ] The heading is displayed
- [ ] Filter button is displayed
- [ ] on tap, user has 9 filter options; 0,1,2,3,4,5,6,7 remaining days and more than 8 remaining days
- [ ] List of filtered items appears in the below section 
- [ ] If no items match the selected filter, a message "No items match the selected filter" is displayed

### Tasks

- [ ] Create new feature branch "feature/FilterButton"
- [ ] Create the component FilterButton
- [ ] Create filter function that filters the products based on the selected filter

size: M
